[
  {
    "cmd": [
      "echo",
      "3pp/"
    ],
    "env": {
      "CIPD_CACHE_DIR": "[CLEANUP]/tmp_tmp_1"
    },
    "name": "echo package_prefix"
  },
  {
    "cmd": [
      "vpython",
      "-u",
      "RECIPE_MODULE[recipe_engine::file]/resources/fileutil.py",
      "--json-output",
      "/path/to/tmp/json",
      "glob",
      "[CACHE]/builder/package_repo",
      "*/3pp.pb"
    ],
    "env": {
      "CIPD_CACHE_DIR": "[CLEANUP]/tmp_tmp_1"
    },
    "infra_step": true,
    "name": "find package specs",
    "~followup_annotations": [
      "@@@STEP_LOG_LINE@glob@[CACHE]/builder/package_repo/[CACHE]/path/something/3pp.pb@@@",
      "@@@STEP_LOG_END@glob@@@"
    ]
  },
  {
    "cmd": [],
    "name": "load package specs"
  },
  {
    "cmd": [
      "vpython",
      "-u",
      "RECIPE_MODULE[recipe_engine::file]/resources/fileutil.py",
      "--json-output",
      "/path/to/tmp/json",
      "copy",
      "[CACHE]/builder/package_repo/[CACHE]/path/something/3pp.pb",
      "/path/to/tmp/"
    ],
    "env": {
      "CIPD_CACHE_DIR": "[CLEANUP]/tmp_tmp_1"
    },
    "infra_step": true,
    "name": "load package specs.read 'something'",
    "~followup_annotations": [
      "@@@STEP_NEST_LEVEL@1@@@",
      "@@@STEP_LOG_LINE@3pp.pb@create {}@@@",
      "@@@STEP_LOG_END@3pp.pb@@@"
    ]
  },
  {
    "cmd": [
      "vpython",
      "-u",
      "RECIPE_MODULE[recipe_engine::file]/resources/fileutil.py",
      "--json-output",
      "/path/to/tmp/json",
      "glob",
      "[CACHE]/builder/dup_repo",
      "*/3pp.pb"
    ],
    "env": {
      "CIPD_CACHE_DIR": "[CLEANUP]/tmp_tmp_1"
    },
    "infra_step": true,
    "name": "find package specs (2)",
    "~followup_annotations": [
      "@@@STEP_LOG_LINE@glob@[CACHE]/builder/dup_repo/[CACHE]/path/something/3pp.pb@@@",
      "@@@STEP_LOG_END@glob@@@"
    ]
  },
  {
    "cmd": [],
    "name": "load package specs (2)",
    "~followup_annotations": [
      "@@@STEP_EXCEPTION@@@"
    ]
  },
  {
    "cmd": [],
    "name": "RECIPE CRASH (Uncaught exception)",
    "~followup_annotations": [
      "@@@STEP_EXCEPTION@@@",
      "The recipe has crashed at point 'Uncaught exception'!",
      "",
      "Traceback (most recent call last):",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/internal/engine.py\", in run_steps",
      "    raw_result = recipe_obj.run_steps(api, engine)",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/internal/recipe_deps.py\", in run_steps",
      "    properties_def, api=api)",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/internal/property_invoker.py\", in invoke_with_properties",
      "    arg_names, **additional_args)",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/internal/property_invoker.py\", in _invoke_with_properties",
      "    return callable_obj(*props, **additional_args)",
      "  File \"RECIPE_REPO[infra]/recipes/recipe_modules/support_3pp/tests/full.py\", line 48, in RunSteps",
      "    builder.join('dup_repo'))",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/recipe_api.py\", in _inner",
      "    return func(*a, **kw)",
      "  File \"RECIPE_REPO[infra]/recipes/recipe_modules/support_3pp/api.py\", line 559, in load_packages_from_path",
      "    raise DuplicatePackage(pkg)",
      "DuplicatePackage: something"
    ]
  },
  {
    "failure": {
      "humanReason": "Uncaught Exception: DuplicatePackage('something',)"
    },
    "name": "$result"
  }
]